---
- name: MariaDB server is running
  hosts: webserver
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
      - httpd

  tasks:
    - name: MariaDB packages are installed
      yum:
        name: "{{ item }}"
        state: absent
      loop: "{{ mariadb_packages }}"
~                                                                                                                         
~                                                                                                                         
~                                          
