---
- name: Recurring cron job
  hosts: serverb
  become: true
  tasks:
    - name: Crontab file exists
      cron:
        name: Add date and time to a file
        minute: "*/1"
        hour: 9-20
        weekday: 1-5
        user: student
        job: date >> /home/student/my_date_time_cron_job
        cron_file: add-date-time
        state: present
~                                                                                                                         
~                                 
