---
- name: Use the fetch module to retreive secure log files
  hosts: all
  remote_user: student

  tasks:
    - name: Fetch the /var/log/secure log file from managed hosts
      fetch:
        src: /var/log/secure
        dest: secure-backups
        flat: no
~                              
